system76/firmware-open

.gitmodules
models/darp5/ec.config
models/darp6/ec.config
models/galp3-c/ec.config
models/galp4/ec.config
models/lemp9/ec.config
scripts/_build/ec.sh
scripts/build.sh
scripts/flash.sh

Build and flash the EC firmware for supported models, using the same version as the board firmware.
Ref: #75

Build and flash  EC firmware

---

scripts/deps.sh

Can't actually test this on Fedora 32 since building crossgcc fails with GCC 10.

Add deps for Fedora/CentOS

---

README.md.in

Changed to match README.md change in #102

README.md.in: update supported models

---

README.md
README.md.in
scripts/deps.sh

- Add note about state of Intel Management Engine
- Remove cargo-xbuild as a dependency

Add note about IME

---

README.md
docs/README.md
docs/adding-a-new-board.md
scripts/coreboot-gpio.sh
scripts/coreboot-hda.sh
scripts/generate.sh

Initial guide for adding support for a new system.
TODO:

Add doc for supporting a new board

---

scripts/deps.sh

- Remove extra `then` to fix running this script
- Update messages for system dependencies
- Add `--progress` for submodule clones, which can get slow

scripts: Fix installing deps

---

docs/adding-a-new-board.md

These values were originally comments in every devicetree. Add them here for now.

docs: Commands to collect some devicetree values

---

scripts/coreboot-gpio.sh

Use the shorter form for GPOs without termination.

scripts: Use PAD_CFG_GPO if there is no pull

---

scripts/_build/edk2.sh

Fixes builds on 21.04
Includes https://github.com/system76/edk2/pull/32

Fixes for python 3.9

---

CHANGELOG.md

Fix brightness controls on TGL

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

github: Add issue template

---

scripts/qemu.sh

Fixes performance issues when running a QEMU VM.
Resolves: #299

qemu: Enable KVM

---

CHANGELOG.md

darp8: Fix SATA detection

---

CHANGELOG.md

Fix power limit config override so board does not power off under load while on battery power.
- system76/coreboot#118

lemp11: Fix PL2/PL4 power limits

---

CHANGELOG.md

Adjust PL2 and PsysPL2 to prevent the system powering off while compiling the kernel on battery power.

oryp9: Fix power off on battery power

---

CHANGELOG.md

- https://github.com/system76/coreboot/pull/142
- https://github.com/system76/ec/pull/305

lemp11: Apply PMC hack to fix S0ix

---

CHANGELOG.md
rust-toolchain.toml

Match the toolchain used by Redox.
- https://github.com/system76/firmware-update/pull/56
- https://github.com/system76/firmware-setup/pull/24
- https://github.com/system76/ec/pull/274

Update Rust toolchain to 2022-03-18

---

CHANGELOG.md

- adl-p: Fix case where system gets stuck in S5 due to power loss
- tgl-u: Fix case where system gets stuck in S5 due to power loss
- galp5: Fix power off failing due to WLAN GPIO

ec: Fix power off issues on ADL and TGL

---

CHANGELOG.md

Configure WLAN GPIOs at the correct point so they are enabled at boot.
Fixes: 5f1ef1731e67 ("ec: Fix power off issues on ADL and TGL")

ec: Fix WLAN power on

---

scripts/deps.sh

fixed a small typo that caused scripts/deps.sh to fail for arch users.

fixed flag for pacman --noconfirm

---

CHANGELOG.md
FEATURES.md
README.md

View the matrix here: https://github.com/system76/firmware-open/blob/77abfadf24c9a0c45ae042cd71d3ce7be26c846e/FEATURES.md

Add feature matrix

---

CHANGELOG.md

Draft until submodule changes are merged:
- https://github.com/system76/coreboot/pull/175
- https://github.com/system76/firmware-update/pull/83

Updates for oryp9/oryp10

---

CHANGELOG.md

coreboot:
- addw3: Enable support for 5200 MT/s memory
- bonw15: Enable support for 5200 MT/s memory
- serw13: Enable support for 5200 MT/s memory
- rpl: Enable TPM read delay to fix occasional failures with Infineon chips
- Perform TPM Restart if TPM Resume fails
ec:
- darp9: Converted to new keyboard
- oryp11: Added new keyboard
- Acknowledge PECI-over-eSPI transactions when finished

Update coreboot and ec

---

FEATURES.md

Add the release dates for the remaining RPL boards and update the addw3 release for the Windows 11 BSOD fix.

Update RPL boards in FEATURES

---

CHANGELOG.md

Brings in the changes to resolve:
- Resolves: #78
- Resolves: #393
- Resolves: #424

Update EC and coreboot

---

CHANGELOG.md

2023-07-19_05cfb1a has been released for several models.

changelog: Add section for 2023-07-19

---

rust-toolchain.toml

All components have been updated to this version.

Update Rust toolchain to nightly-2023-01-21

---

CHANGELOG.md

- Enable `CnviBtAudioOffload` to fix issues with BT
Ref: https://github.com/system76/coreboot/pull/191

coreboot: Fix Bluetooth performance on TGL

---

Jenkinsfile

Ref: https://www.jenkins.io/doc/book/pipeline/
Ref: https://buildchain.system76.com/pipeline-syntax/
- Basic messages added
- Must be sequential due to reusing workspace
- Set up a local instance

Add Jenkinsfile for Pipeline

---

Jenkinsfile
scripts/deps.sh

Now that #306 is merged and can be tested again the real build server, address some issues that came up during the set up of a new Pipeline job.

Fix Jenkinsfile

---

CHANGELOG.md

Fixes https://github.com/system76/windows-drivers/issues/21

Update coreboot and changelog

---

Jenkinsfile

- Use `GIT_COMMIT` instead of stashing the commit
- Do not shadow built-in `GIT_BRANCH` variable with a parameter
- Update `scmGit` config based on docs

Jenkins: Misc changes

---

rust-toolchain.toml

TODO: Update firmware-setup to new toolchain

Update Rust toolchain to 2023-09-07

---

CHANGELOG.md
LICENSE.md
README.md
docs/README.md
docs/SUMMARY.md
docs/book.toml
docs/building.md
docs/features.md
docs/index.md
docs/schematics.md

Allow generating HTML output of docs for easy navigation and reading.

Build docs with mdBook

---

CHANGELOG.md

Brief summary of primary changes:
- darp10: Fixes for TCSS, fans
- bonw15-b: Add new board
- Update fan mechanisms

add bonw15-b, darp10 fixes, EC fan update

---

CHANGELOG.md

- https://github.com/system76/coreboot/pull/238

Update coreboot to 24.08

---

CHANGELOG.md

edk2: Enable boot timeout control via "Timeout"

---

CHANGELOG.md

Ref: https://github.com/system76/coreboot/pull/241

coreboot: Update ucode to microcode-20241112

---

scripts/build.sh
scripts/usb.sh

Fixes: 618a266e7027 ("scripts: Split creating USB image to separate script")

scripts: Fix adding SBIOS firmware to USB

---

CHANGELOG.md
docs/building.md

- https://github.com/system76/coreboot/pull/253

Update coreboot to 25.03
