system76/firmware-open

- scripts/deps.sh
- Pin compiler-builtins to 0.1.27
- 0.1.28 uses the new [`llvm_asm!`](https://github.com/rust-lang/rfcs/pull/2843) macro
- Install cargo-xbuild 0.5.29
- 0.5.32 passes new arguments for LTO which older toolchains don't recognize
> Pin dependencies to fix build with current toolchain

- scripts/_build/edk2.sh
Rebase on the latest stable tag of EDK II, switching from CorebootPayloadPkg to the new UefiPayloadPkg.
> Rebase edk2 on edk2-stable202002

- README.md
The System76 website mentions these models coming with open firmware, so presumably they count as supported.
Perhaps a table summarizing the status of each port could be helpful...
> README.md: update mention of supported models

- docs/adding-a-new-board.md
Should I add this to [smart-amp](https://github.com/system76/smart-amp) instead?
> docs: TAS5825M porting information

- scripts/deps.sh
My build failed on a Pop!_OS-Live-Stick until I installed `libudev-dev`. I don't remember if it was the firmware-open or the ec build that failed, but ec references deps.sh.
> Added libudev-dev for Pop!_OS

- .gitignore
- scripts/deps.sh
- scripts/extract.sh
- scripts/generate.sh
Update UEFITool to the `new_engine` branch and add a script to build/use UEFIExtract.
Automate extracting the Intel GOP driver when generating data for a new model.
> Extract IntelGopDriver when generating new model data

- models/addw1/IntelGopDriver.efi
- models/addw2/IntelGopDriver.efi
- models/darp5/IntelGopDriver.efi
- models/darp6/IntelGopDriver.efi
- models/galp3-c/IntelGopDriver.efi
- models/gaze15/IntelGopDriver.efi
- models/lemp9/IntelGopDriver.efi
- models/oryp5/IntelGopDriver.efi
- models/oryp6/IntelGopDriver.efi
Using the Intel GOP driver from proprietary firmware has resolved some
issues with the lemp10. Use UEFIExtract from UEFITool to extract the GOP
driver from the proprietary firmware for other boards.
./UEFIExtract <firmware.rom> 7755CA7B-CA8F-43C5-889B-E1F59A93D575 -o extract
The version we have been using is what is present in gaze14.
Most of the galp models did not have IntelGopDriver in the extract.
> Use Intel GOP driver from proprietary BIOS

- scripts/deps.sh
Fedora has apt packaged, which causes this script to do the wrong
thing if it is installed. Instead of checking for the package manager
binary, use `os-release(5)` data to select the correct package manager
to use.
> scripts/deps.sh: Use os-release(5) to select correct package manager

- scripts/deps.sh
Saves time and prevents errors with trying to install rustup twice or potentially overriding the user's default toolchain.
> deps: Skip installing Rust if rustup is available

- docs/intel-me.md
Explain why we ship galp5/lemp10 with the IME enabled.
Info from [Jeremy's response on reddit](https://www.reddit.com/r/System76/comments/k0g971/intel_me_enabled_in_new_lemur_and_galago/gdke4yt/).
> docs: Add note about IME state on TGL-U

- scripts/_build/coreboot.sh
If a board in `models/` does not exist in coreboot, coreboot will emit a warning and select the first available board for the vendor instead.
This may result in building and being able to flash coreboot with an addw1 configuration on another board.
> scripts: Check coreboot config is correct

- scripts/build.sh
- scripts/pxestick.sh
Debian does not export `/usr/bin` in `PATH` for users like every other distro so builds fail to find mkfs and parted.
Fixes: #95
> Fix building on Debian

- CHANGELOG.md
- README.md
- README.md.in
This is built from the changelogs we use to describe firmware updates. I have ensured the earliest date including the change in released firmware is used, and I don't think there are any conflicts where firmware was released after these dates without including the mentioned changes.
> Add changelog

- rust-toolchain
- scripts/deps.sh
rustup 1.23.0 (2020-11-27) introduced support for TOML syntax for the
toolchain file. Use this and specify required compoenents.
To ensure you are using a new enough rustup, run:
rustup self update
> Convert toolchain file to TOML syntax

- CHANGELOG.md
This may address https://github.com/system76/firmware-open/issues/129. First functionality of systems with Synaptics touchpad should be verified. Then I will produce USB images for the affected users to try. Includes and requires https://github.com/system76/coreboot/pull/58
**Please provide `dmesg` output before and after installing!**
- Download [gaze15-touchpad.zip](https://github.com/system76/firmware-open/files/6172736/gaze15-touchpad.zip)
- Extract `gaze15-touchpad.img`
- Use Popsicle to flash to a USB drive
- Boot from the USB drive and follow the instructions to flash the firmware
> gaze15: Add ELAN touchpad settings

- CHANGELOG.md
Update coreboot to pull in changes that fix USB-C on galp3-c.
Remove darp5/galp3-c from the changelog as they have not been released.
> Fix USB-C on galp3-c

- scripts/deps.sh
Only qmake was needed, not all of qt5-base, but UEFITool/UEFIExtract can be built only requiring CMake.
> deps: Remove qt5 and clean up Arch pkgs

- scripts/deps.sh
Install `python-is-python3` to provide the `/usr/bin/python` symlink.
Fixes installing dependencies on Pop!_OS 21.10.
Should be checked it still works on 20.04.
> scripts: Update pkg for python symlink

- CHANGELOG.md
> gaze16: Fix using USB 2.0 devices in Type-C port

- scripts/deps.sh
coreboot requires python2 explicitly when using the FSP submodule as the source for FSP binaries.
python2 3rdparty/fsp/Tools/SplitFspBin.py ...
Resolves: #251
> scripts: Add Python2 to deps

- CHANGELOG.md
- Fix lemp10 memory info to prevent an error message in cbmem.
- Fix booting lemp10 with DIMM not present.
Resolves: #269
> coreboot: Fix lemp10 boot

- scripts/build.sh
Specify `abbrev` to ensure the length of the commit hash is always the same, in case `core.abbrev` is set or the default changes.
> build.sh: Set git-describe length

- .gitmodules
- tools/README.md
The [Positive Technologies](https://github.com/PositiveTechnologies) org is no longer available on GitHub. As these tools were never directly used, just remove them.
> Remove unME11/unME12

- models/gaze17-3060-b/me.rom
This sets up the FPFs to be committed on the first boot. It does not lock flash descriptor settings, intentionally.
> gaze17-3060-b: run end of manufacturing on first boot

- LICENSE.md
- LICENSES/BSD-2-Clause-Patent.txt
- LICENSES/GPL-2.0-only.txt
- LICENSES/GPL-3.0-only.txt
- LICENSES/Intel-redist.txt
Resolves: #263
What's the license info for other binaries used?
- `fd.rom`
- `vbt.rom`
- `usb4-retimer.rom` (do we actually use this anywhere?)
- `shell.efi`
- `uecflash.efi`
- `meset.efi`
- `IntelGopDriver.efi`
> Add info and text for firmware binaries licenses

- scripts/_spipi.sh
Improved config script so the spipi config file doesn't have
to be updated with the IP address of the raspberry pi.
> Set spipi to new name instead of IP address

- scripts/_build/edk2.sh
- scripts/deps.sh
This ensures the same version of GCC is used for building coreboot and the payload.
Test:
- Can build any board from an existing checkout that has been updated
- Can build any board on a fresh OS install after running `./scripts/deps.sh`
Resolves: #334
See also: #313
> Use coreboot toolchain for building edk2

- CHANGELOG.md
The `gfx` register got dropped during some rebase. Add them back.
Fixes brightness controls on Windows for oryp8, gaze16, lemp9.
Fixes: #355
> coreboot: Fix brightness controls

- CHANGELOG.md
- charger: Limit charger values to max valid value
- charger/bq24780s: Set RSENSE ratio option
- charger/bq24780s: Fix charge current mask
- oryp[5-8]: Reduce charge current to 2A
Requires: system76/ec#303
> ec: Fix charger values

- CHANGELOG.md
Fixes board failing to reach S0ix most of the time.
lemp11 still sometimes fails to reach C10, but plugging/removing AC adapter still works to fix it.
> lemp11: Remove CARD RTD3 config

- CHANGELOG.md
Reload PWM counters when they reach 0 instead of immediately.
Approved in: system76/ec#304
Fixes: system76/ec#174
> ec: Fix KB backlight color with custom values

- CHANGELOG.md
Remove CPU PCIe RP RTD3 config on TGL-U and ADL-P. Fixes suspend with some drives, such as WD Blue.
- https://github.com/system76/coreboot/pull/146
> coreboot: Remove CPU PCIe RP RTD3 configs

- CHANGELOG.md
Hook up GMA ACPI brightness controls for ADL and set the gfx register for ADL boards.
Fixes backlight controls on Windows 10 and Linux 6.1.
Change approved in: https://github.com/system76/coreboot/pull/147
> coreboot: Fix ACPI brightness controls on ADL

- CHANGELOG.md
After changing EC detection of S0ix from `CPU_C10_GATE#` to `SLP_S0#`, DevSlp blocks S0ix entry. Disable it for now on TGL-U and ADL-P.
Ref: https://github.com/system76/coreboot/pull/148
> coreboot: Disable SATA DevSlp on S0ix boards

- .github/ISSUE_TEMPLATE/bug_report.md
Issues may depend on changes that happened in the kernel, such as:
- TBT using software CM instead of firmware CM
- TGL GPIO communities changing to match Windows
- Removal of `intel_backlight`
> Ask for kernel version for bug reports

- scripts/flash.sh
- scripts/qemu.sh
Implements https://github.com/system76/firmware-open/issues/158
To test this, install it on an open EC laptop and run:
```
cd firmware-open/ec
./ectool.sh security unlock
reboot
```
You can check the current lock status with:
```
./ectool.sh security
```
Includes:
- https://github.com/system76/coreboot/pull/54
- https://github.com/system76/ec/pull/146
- https://github.com/system76/edk2/pull/28
- https://github.com/system76/firmware-setup/pull/18
- https://github.com/system76/firmware-update/pull/35
> Firmware locking

- CHANGELOG.md
This brings in the following changes:
- Set PL4 based on AC state for all boards
- Increase PL4 on battery to 45W for dGPU boards
- galp6,galp7: Enable firmware security
> ec: Update for galp7

- scripts/deps.sh
Some coreboot submodules have their update strategy set to "none". They will not be cloned/updated unless `--checkout` is specified.
Fixes building after cloning firmware-open and running `deps.sh`.
> scripts: Force submodule checkout

- scripts/build.sh
Fixes building when `log.showSignature` is enabled.
> scripts: Disable showing signature when getting date

- CHANGELOG.md
DBX version 371 was released on 2023-05-09.
Ref: https://uefi.org/revocationlistfile
> edk2: Update Secure Boot DBX to version 371

- CHANGELOG.md
This brings in https://github.com/system76/coreboot/pull/180 and https://github.com/system76/ec/pull/371, required for bonw15 release.
> Update coreboot and ec

- .gitmodules
- libs/README.md
- libs/README.md.in
- scripts/readmes.sh
These are at best a convenience for working on them. They are not used directly by firmware-open, only as dependencies in other projects.
- coreboot-table: Dependency of apps/firmware-setup
- coreboot-fs: Dependency of apps/firmware-update and libs/intel-spi
- intel-spi: Dependency of apps/firmware-update
- intelfash: Dependency of apps/firmware-update and scripts/modeltool
- uefi: Dependency of a lot of stuff
> Remove libs/

- docs/debugging.md
Closes #454.
The full GitHub link won't be seamless with mdBook if https://github.com/system76/firmware-open/pull/383 is merged, but doing some quick web searching, I don't see a way to have a relative link into a submodule file (at least that will work here on GitHub).
The old link seemed to be outdated even if it was being dealt with locally (the directory is currently `docs`, not `doc`).
> fix (docs): Update link to EC debugging

- CHANGELOG.md
- gaze16: Fixed CPU not going lower than C2 due to card reader LTR
- adl: Fixed CPU not going lower than C2 due to card reader LTR
- rpl: Fixed CPU not going lower than C2 due to card reader LTR
- Changed battery charge start threshold to 90%
- Changed charger to disable when battery is full
> Update coreboot and EC for power fixes

- Jenkinsfile
The scripted projects using the default Slack notifications settings report the time the build took. Add it to the declarative jobs as well.
> jenkins: Add build duration to Slack notifications

- docs/intel-me.md
I had forgotten that CSME reporting an error was normal when disabled. Document what is should report when enabled/disabled.
> docs: Add note about checking CSME state

- CHANGELOG.md
Allow using 5600 MHz RAM on addw3, bonw15, and serw13.
> coreboot: rpl-hx: Add support for 5600 MHz RAM

- scripts/_build/ec.sh
Specify the EC build directory so that it does not require the model or version to be determined in the script.
This will allow building currect EC master with firmware-open master.
> scripts: Set EC build dir

- CHANGELOG.md
Fix a potential lock up during S0ix opportunistic suspend, caused by waiting indefinitely for a PECI command to complete when it is not available.
> ec: Fix lock up during opportunistic suspend

- scripts/_build/ec.sh
Building EC was broken as the build output from the previous board was not being cleaned. `BUILD` is now always set, defaulting to "build", instead of only when `BOARD` is specified. For good measure, add it to the clean command in case a custom path is used.
Fixes: 569321f9ac79 ("scripts: Set EC build dir")
> scripts: Always set EC build dir

- CHANGELOG.md
Fix programming the LTR so that CPU can reach C-states deeper than C2.
> coreboot: Fix OZ711LV2 LTR for galp5 3050 variant

- scripts/_build/edk2.sh
- scripts/build.sh
Allow overriding the coreboot toolchain location with `XGCCPATH` so that xgcc can be installed to a separate location, such as `/opt`.
> Set and use `XGCCPATH`

- scripts/_build/coreboot.sh
- scripts/coreboot-sdk.sh
- scripts/install-deps.sh
Specify dependencies specifically for building coreboot toolchains in the file, so they are not conflated with the dependencies required for building firmware-open.
Remove building the toolchain when building firmware, so that the new script is the single source for building coreboot toolchains.
> Split building coreboot toolchains to a separate file

- CHANGELOG.md
Just enable the BayHub driver on everything.
Ref: https://github.com/system76/coreboot/pull/198
Resolves: https://github.com/system76/firmware-open/issues/491
> coreboot: Fix LTR for card reader on TGL-U boards

- scripts/_build/coreboot.sh
- scripts/_build/ec.sh
- scripts/_build/edk2.sh
- scripts/_ch341a.sh
- scripts/_spipi.sh
- scripts/build.sh
- scripts/ch341a-dump.sh
- scripts/ch341a-flash.sh
- scripts/coreboot-gpio.sh
- scripts/flash.sh
- scripts/fsp_params.sh
- scripts/generate.sh
- scripts/install-deps.sh
- scripts/qemu.sh
- scripts/readmes.sh
- scripts/realtek-coeffs.sh
- scripts/remotes.sh
- scripts/spipi-dump.sh
- scripts/spipi-erase.sh
- scripts/spipi-flash.sh
- scripts/spipi.sh
Report issues by shell files with:
git ls-files '*.sh' | xargs shellcheck --exclude=SC2162
Address the following:
- [SC1087](https://www.shellcheck.net/wiki/SC1087): Use braces when expanding arrays
- [SC1091](https://www.shellcheck.net/wiki/SC1091): Not following
- [SC2004](https://www.shellcheck.net/wiki/SC2004): `$`/`${}` is unnecessary on arithmetic variables
- [SC2024](https://www.shellcheck.net/wiki/SC2024): `sudo` doesn't affect redirects
- [SC2034](https://www.shellcheck.net/wiki/SC2034): foo appears unused. Verify it or export it
- [SC2086](https://www.shellcheck.net/wiki/SC2086): Double quote to prevent globbing and word splitting
- [SC2087](https://www.shellcheck.net/wiki/SC2087): Quote `EOF`
- [SC2115](https://www.shellcheck.net/wiki/SC2115): Use `"${var:?}"` to ensure this …
> scripts: Address shellcheck issues

- CHANGELOG.md
Ref: https://github.com/system76/coreboot/pull/199
Resolves: https://github.com/system76/firmware-open/issues/495
> coreboot: Fix bonw15, oryp11 speaker output

- docs/uefi.md
Secure Boot support is enabled. Make it clear in the doc that it was enabled so Windows could be installed, and not as a means for securing the system.
> docs: Update note about Secure Boot support

- CHANGELOG.md
Avoid the issue on new boards where the PCH will not de-assert the `PLTRST#` virtual wire on S3 resume, causing the unit to hang.
Ref: system76/firmware-open#469
Ref: system76/coreboot#203
> darp8,darp9: Use S0ix by default

- CHANGELOG.md
Fixes suspend with the following drives:
- Kingston KC3000 (SKC3000D/4096G)
- Kingston HyperX (SHPM2280P2H/240G)
- Solidigm P44 Pro (SSDPFKKW010X7)
Ref: system76/coreboot#192
> darp9: Add SSD RTD3 configs

- docs/intel-me.md
CSME should be enabled when S0ix is used for power savings during suspend. TGL-U is just one case where we default as our TGL-U models do not support S3. Other models may use S0ix as well, such as darp8 and darp9 due to new batches just not working with S3 anymore [1].
[1]: https://github.com/system76/firmware-open/issues/507
> docs: Update CSME note about S0ix/TGL-U

- scripts/install-rust.sh
Commit 7d6a15e63c95 ("Convert toolchain file to TOML syntax") switched from the bare toolchain file to the TOML-based one for better management of the toolchain and components used.
Commit cf7fc2c540d5 ("scripts: Update rustup or inform user of env vars") added an explicit `rustup self update` because there were still cases, a year later, of people not having a rustup new enough to support the TOML-based toolchain file.
Now 2 years after that, it should be safe to drop the explicit self update. The TOML format has widespread adoption and rustup now self updates by default. This should allow distro-provided rustup, which disables the self update feature, to work if it is already installed in place of the one downloaded from https://rustup.rs.
> scripts: Remove explicit rustup self update

- scripts/install-deps.sh
It looks like attempting to build firmware on a clean Pop-OS 22.04 or Fedora 39 install requires additional dependencies not furnished by our install scripts.
This adds those dependencies in correct alphabetical location within their respective parts of the dependencies script. 
- `libssl-dev` and ~~`pkg-config`~~ `pkgconf` for Pop-OS 
- `openssl-devel` for Fedora
I saw no issues with the Arch dependencies in brief testing.
> Add Debian and Fedora dependencies

- CHANGELOG.md
Caching ramtop does not update the checksum, causing CMOS options to not work. Fixes CSME not being disabled on first boot.
> coreboot: Fix CMOS options checksum

- docs/flashing.md
- scripts/flash.sh
As somewhat of a hack, allow flashing only the EC by deleting the `firmware.rom` file before running `flash.sh`.
`flash.sh` was changed from internally flashing to using the UEFI application (firmware-update). The option `--without-ec` was removed as part of this.
>  Allow flashing EC only, update docs on flashing

- CHANGELOG.md
- rust-toolchain.toml
Update toolchain to match the version used in Redox.
firmware-setup is still stuck on nightly-2023-01-21.
> Update Rust toolchain to nightly-2024-05-11

- CHANGELOG.md
Clear PS/2 status to prevent data for writes being detected on reads, which was causing drivers to stop working.
> ec: Fix touchpad in PS/2 mode

- CHANGELOG.md
- models/darp6/README.md
- models/darp6/me.rom
- models/galp4/README.md
- models/galp4/me.rom
- models/lemp9/README.md
- models/lemp9/me.rom
Update CSME to the version from CML-U IPU 24.3 (Kit 813939).
Test:
- CSME can be enabled/disabled via coreboot CMOS option
- System boots
- System completes suspend cycle
- System powers off when shutdown
> cml-u: Update CSME to 14.1.74.2355v6

- CHANGELOG.md
- models/addw2/README.md
- models/addw2/me.rom
- models/bonw14/README.md
- models/bonw14/me.rom
- models/darp6/README.md
- models/darp6/me.rom
- models/galp4/README.md
- models/galp4/me.rom
- models/gaze15/README.md
- models/gaze15/me.rom
- models/lemp9/README.md
- models/lemp9/me.rom
- models/oryp6/README.md
- models/oryp6/me.rom
- models/oryp7/README.md
- models/oryp7/me.rom
Update CSME to the version from CML-S/H BKC IPU 2024.3 (Kit 817210).
Test:
- CSME can be enabled/disabled via coreboot CMOS option
- System boots
- System completes suspend cycle
- System powers off when shutdown
> cml-h: Update CSME to 14.1.74.2355v6

- CHANGELOG.md
The EC will already be set to unlocked at this point, so the prompt must be run even when in the "Unlock" state. This is fine, as the prompt is for physical presence detection.
Only lemp13-b has a release affected by this change. Meaning, this update will not show the prompt when users update, but the firmware update _after_ this one will start showing the prompt again.
On all other systems, the firmware will still show the unlock prompt as expected.
Resolves: #562
> firmware-setup: Revert unlock prompt change

- rust-toolchain.toml
Remove rust-src as it is not required. Use a minimal profile with clippy and rustfmt installed, instead of the default profile, as rust-docs is not needed.
> Update Rust toolchain config

- CHANGELOG.md
Decouple the fan logic from the dGPU logic. Firmware now supports a second fan on systems without a dGPU, such as darp10.
Behavioral changes:
- ectool: Fans are now indexed from 1 instead of 0
- Linux: darp10 now reports details about the second fan
Requires:
- https://github.com/system76/ec/pull/474
- https://github.com/system76/coreboot/pull/222
> Add support for second fan without a dGPU

- CHANGELOG.md
- models/addw1/README.md
- models/addw1/me.rom
- models/gaze14_1660ti/README.md
- models/gaze14_1660ti/me.rom
- models/oryp5/README.md
- models/oryp5/me.rom
Update CSME to the version from CFL-S/H IPU 24.1 (Kit 792171).
(I couldn't find a 2024-03 IPU/BKC like everything else.)
Test:
- CSME can be enabled/disabled via coreboot CMOS option
- System boots
- System completes suspend cycle
- System powers off when shutdown
> cfl-h: Update CSME to 12.0.94.2380v9

- containers/firmware-open/Containerfile
- Change image from trixie-20240701-slim to bookworm-20241016-slim
- unstable doesn't keep GNAT in sync with GCC, which causes problems when compiling coreboot SDK
- Update coreboot SDK from 24.02 to 24.08
- Match coreboot submodule base
- Add workaround for bug in rustup 1.27
- Add link to firmware-setup issue to track toolchain blocker
- Put `&&` at beginning of all chained commands for consistency, and to reduce the diff if commands are added/removed
Locally built image is 3.77 GiB.
> Update container file

- scripts/build.sh
- scripts/usb.sh
The USB image is not a required output, but becomes half of the total size of the build artifacts as it creates copies of the firmware images. Move the logic to a separate script so that CI will not contain it, but users can create the image after building the firmware.
./scripts/build.sh <model>
./scripts/usb.sh <model>
Reduces the size of the ZIP archive created by Jenkins by ~50%.
```
$ ls -lh build/darp10/
total 90M
-rw-r--r--. 1 tcrawford tcrawford 256K Feb 28 15:40 ec.rom
-rw-r--r--. 1 tcrawford tcrawford  32M Feb 28 15:40 firmware.rom
-rw-r--r--. 1 tcrawford tcrawford 8.0M Feb 28 15:40 UEFIPAYLOAD.fd
-rw-r--r--. 1 tcrawford tcrawford  49M Feb 28 15:40 usb.img
```
> scripts: Split creating USB image to separate script

- .github/workflows/ci.yaml
- LICENSES/CC0-1.0.txt
- docs/building.md
- scripts/coreboot-sdk.sh
- scripts/install-deps.sh
- scripts/install-rust.sh
TODO:
- Determine cache storage usage/cost
- coreboot toolchain is using 160 MB, and apparently there's 10 GB available
- Determine artifact storage usage/cost
- disabled upload-artifact for now because it's going to be a lot of space
- Replace script in private firmware repo for downloading build artifacts when staging updates
- depends on uploading artifacts
- Investigate reducing CI time, esp. on cloning all the submodules and installing build dependencies
- Limit the models built by default to not hit concurrency limit?
- But would want a way to manually trigger a build by specifying models like Jenkins currently does
> ci: Add GitHub Actions

- .github/workflows/ci.yaml
- Only checkout the coreboot submodule for building the toolchain
- Don't restore the cache when checking if we need to build the toolchain
Reduces toolchain job time from ~2.5m to ~20s (when it doesn't need to be rebuilt).
> ci: Speed up toolchain job

- scripts/coreboot-sdk.sh
The NASM website has been offline for days. Use the coreboot mirror to fix building the toolchain.
> scripts: Use coreboot mirror for building toolchain

- Jenkinsfile
Does Groovy parse the running script line-by-line? Apparently, `+` must exist on the starting line for it to know that the next line is a continuation.
Fixes: 99ffbf9bdb60 ("jenkins: Add darp11, darp11-b")
> jenkins: Fix string concat
